services:
    db:
        image: postgres:17.4
        environment:
            POSTGRES_USER: sql
            POSTGRES_PASSWORD: sql
            POSTGRES_DB: sql
        ports:
            - 5434:5432
