services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: sqlant_user
            POSTGRES_PASSWORD: sqlant_pswd
            POSTGRES_DB: sqlant_db
        ports:
            - 5432:5432
    adminer:
        image: adminer
        ports:
            - 8080:8080
